# Generated by Django 4.2.3 on 2023-07-16 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
