# Generated by Django 4.2.3 on 2023-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
