# Generated by Django 4.2.3 on 2023-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_chemistry_image_chemistry_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
