# Generated by Django 4.2.3 on 2023-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_chemistry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublished', max_length=200),
        ),
    ]
