# Generated by Django 4.2.3 on 2023-07-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_chemistry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry',
            name='levels',
            field=models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50),
        ),
    ]
