# Generated by Django 4.2.3 on 2023-07-16 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_chemistry_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublished', max_length=200)),
                ('levels', models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublished', max_length=200)),
                ('levels', models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublished', max_length=200)),
                ('levels', models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
