# Generated by Django 4.2.3 on 2023-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_biology_mathematics_physics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='biology',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='physics',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
    ]
