# Generated by Django 4.2.3 on 2023-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_feedback_alter_biology_levels_alter_chemistry_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='levels',
            field=models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='levels',
            field=models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='levels',
            field=models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='physics',
            name='levels',
            field=models.CharField(choices=[('A-Level', 'A-Level'), ('O-Level', 'O-Level')], default='O-Level', max_length=50),
        ),
    ]
