# Generated by Django 4.2.3 on 2023-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_alter_biology_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
