# Generated by Django 4.2.3 on 2023-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_alter_biology_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='biology',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=200),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=200),
        ),
        migrations.AlterField(
            model_name='physics',
            name='levels',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='physics',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=200),
        ),
    ]
