# Generated by Django 4.2.3 on 2023-07-20 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_alter_biology_levels_alter_biology_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
