# Generated by Django 4.2.3 on 2023-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_biology_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
